### PR TITLE
[WIP] Cleaner url parser and removed http assumption

### PR DESCRIPTION
**Pull request by rosscdh**
updated readme and made pep8 compliant and made url parsing better

### CODE REVIEW

**Comment by ulfur** [comment]
Merged. Thank you for your contribution :)

**Comment by rosscdh** [comment]
O! Hey there, you seem to have merged a [WIP] PR.. sorry but thats Work In
Progress.

No probs, am wondering how up-to-date the lib is tho?

**Comment by ulfur** [comment]
Oh, damn, wasn't paying attention :P
That being said, this isn't a very popular or much used git so I'm fairly sure it'll be fine.

This work is not up-to-date at all. It's something I was working on a while ago but had to abandon due to other projects. I've been meaning to work more on it at some point, probably when I'll have need for it again, but would have to review the status of the Paymill API and any available Python/Django implementations before doing so.

Are you considering using this? If so I'd be happy to give more attention to it and help out in any way that I can.

**Comment by rosscdh** [comment]
Hey man no its no problem, I found it as I was preparing to build my own
integration and was investigating it. (Nice work btw, except for the
various stylistic pylint issues ;) )

Im still evaluating as it woudl have to be integrated with the "new"
official python-wrapper. Might be wroth just doing it again? I'm open to
feedback.

I've started on https://github.com/rosscdh/django-paymill-redux using an
order integration I built for another integration, perhaps you would be
open to working on that together?

Best
Ross

**Pull request merged**
